In [1]:

import pandas as pd

In [2]:

df=pd.read_csv('fake-news/True.csv')

In [3]:
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [4]:
X = df.drop('label', axis=1, errors='ignore')

In [5]:

X.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
y = df[df.columns[-1]]

In [7]:

y.head()

0    December 31, 2017
1    December 29, 2017
2    December 31, 2017
3    December 30, 2017
4    December 29, 2017
Name: date, dtype: object

In [8]:

df.shape

(21417, 4)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [10]:
df=df.dropna()

In [11]:
df.head(10)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017"
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017"
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017"

In [12]:
messages=df.copy()

In [13]:

messages.reset_index(inplace=True)

In [14]:

messages.head(10)

,index,title,text,subject,date
0,0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
5,5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017"
6,6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017"
7,7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
8,8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
9,9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017"

In [15]:

messages['title'][6]

'Trump says Russia probe will be fair, but timeline unclear: NYT'

In [16]:
import re

In [17]:

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
         review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
         review = review.lower()
         review = review.split()
    
         review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
         review = ' '.join(review)
         corpus.append(review)

In [18]:
corpus[3]

'fbi russia probe help australian diplomat tip nyt'

In [20]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()

In [21]:
X.shape

(21417, 5000)

In [22]:
y = df[df.columns[-1]]

In [23]:
## Divide the dataset into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [24]:
cv.get_feature_names_out()[:20]

array(['abadi', 'abandon', 'abba', 'abc', 'abc news', 'abduct', 'abe',
       'abe agre', 'abe say', 'abl', 'abort', 'abort law', 'abroad',
       'absolut', 'abu', 'abus', 'academ', 'accept', 'access', 'accid'],
      dtype=object)

In [25]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [26]:

count_df = pd.DataFrame(X_train, columns=cv.get_feature_names_out())

In [27]:

count_df.head()

,abadi,abandon,abba,abc,abc news,abduct,abe,abe agre,abe say,abl,...,zimbabw militari,zimbabw mnangagwa,zimbabw mugab,zimbabw opposit,zimbabw rule,zimbabw rule parti,zimbabwean,zone,zor,zuma
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:

import matplotlib.pyplot as plt

In [30]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    See full source and example: 
    http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html
    
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, cm[i, j],
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [31]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [32]:

from scipy import sparse
from sklearn.feature_selection import SelectKBest, chi2
from sklearn import metrics
import numpy as np
import seaborn as sns
import itertools

In [33]:
X_train_sparse = sparse.csr_matrix(X_train)
X_test_sparse = sparse.csr_matrix(X_test)

In [34]:
 #Select the best 1000 features based on chi-square test
selector = SelectKBest(chi2, k=1000)
X_train_new = selector.fit_transform(X_train_sparse, y_train)
X_test_new = selector.transform(X_test_sparse)

In [35]:
classifier.fit(X_train_new, y_train)
pred = classifier.predict(X_test_new)

score = metrics.accuracy_score(y_test, pred)
print(f"Accuracy: {score:.4f}")

Accuracy: 0.0313

In [36]:
print("Unique classes in y_test:", np.unique(y_test))
print("Unique classes in pred:", np.unique(pred))

Unique classes in y_test: ['April 1, 2016 ' 'April 10, 2017 ' 'April 11, 2016 ' 'April 11, 2017 '
 'April 12, 2016 ' 'April 12, 2017 ' 'April 13, 2016 ' 'April 13, 2017 '
 'April 14, 2016 ' 'April 14, 2017 ' 'April 15, 2016 ' 'April 16, 2016 '
 'April 17, 2016 ' 'April 17, 2017 ' 'April 18, 2016 ' 'April 18, 2017 '
 'April 19, 2016 ' 'April 19, 2017 ' 'April 20, 2016 ' 'April 20, 2017 '
 'April 21, 2016 ' 'April 21, 2017 ' 'April 22, 2016 ' 'April 22, 2017 '
 'April 23, 2017 ' 'April 24, 2016 ' 'April 24, 2017 ' 'April 25, 2016 '
 'April 25, 2017 ' 'April 26, 2016 ' 'April 26, 2017 ' 'April 27, 2016 '
 'April 27, 2017 ' 'April 28, 2016 ' 'April 28, 2017 ' 'April 29, 2016 '
 'April 3, 2017 ' 'April 30, 2016 ' 'April 30, 2017 ' 'April 4, 2016 '
 'April 4, 2017 ' 'April 5, 2016 ' 'April 5, 2017 ' 'April 6, 2016 '
 'April 6, 2017 ' 'April 7, 2016 ' 'April 7, 2017 ' 'April 8, 2016 '
 'April 8, 2017 ' 'April 9, 2016 ' 'April 9, 2017 ' 'August 1, 2016 '
 'August 1, 2017 ' 'August 10, 2016 ' 'August 10, 2017 '
 'August 11, 2016 ' 'August 11, 2017 ' 'August 12, 2016 '
 'August 12, 2017 ' 'August 13, 2017 ' 'August 14, 2016 '
 'August 14, 2017 ' 'August 15, 2016 ' 'August 15, 2017 '
 'August 16, 2016 ' 'August 16, 2017 ' 'August 17, 2017 '
 'August 18, 2016 ' 'August 18, 2017 ' 'August 19, 2016 '
 'August 19, 2017 ' 'August 2, 2016 ' 'August 2, 2017 ' 'August 20, 2017 '
 'August 21, 2016 ' 'August 21, 2017 ' 'August 22, 2016 '
 'August 22, 2017 ' 'August 23, 2016 ' 'August 23, 2017 '
 'August 24, 2016 ' 'August 24, 2017 ' 'August 25, 2016 '
 'August 25, 2017 ' 'August 26, 2016 ' 'August 26, 2017 '
 'August 27, 2017 ' 'August 28, 2016 ' 'August 28, 2017 '
 'August 29, 2016 ' 'August 29, 2017 ' 'August 3, 2016 ' 'August 3, 2017 '
 'August 30, 2016 ' 'August 30, 2017 ' 'August 31, 2016 '
 'August 31, 2017 ' 'August 4, 2016 ' 'August 4, 2017 ' 'August 5, 2016 '
 'August 5, 2017 ' 'August 6, 2016 ' 'August 6, 2017 ' 'August 7, 2017 '
 'August 8, 2016 ' 'August 8, 2017 ' 'August 9, 2016 ' 'August 9, 2017 '
 'December 1, 2016 ' 'December 1, 2017 ' 'December 10, 2016 '
 'December 10, 2017 ' 'December 11, 2016 ' 'December 11, 2017 '
 'December 12, 2016 ' 'December 12, 2017 ' 'December 13, 2016 '
 'December 13, 2017 ' 'December 14, 2016 ' 'December 14, 2017 '
 'December 15, 2016 ' 'December 15, 2017 ' 'December 16, 2016 '
 'December 16, 2017 ' 'December 17, 2016 ' 'December 17, 2017 '
 'December 18, 2016 ' 'December 18, 2017 ' 'December 19, 2016 '
 'December 19, 2017 ' 'December 2, 2016 ' 'December 2, 2017 '
 'December 20, 2016 ' 'December 20, 2017 ' 'December 21, 2016 '
 'December 21, 2017 ' 'December 22, 2016 ' 'December 22, 2017 '
 'December 23, 2016 ' 'December 23, 2017 ' 'December 24, 2017 '
 'December 25, 2017 ' 'December 26, 2016 ' 'December 26, 2017 '
 'December 27, 2017 ' 'December 28, 2016 ' 'December 28, 2017 '
 'December 29, 2016 ' 'December 29, 2017 ' 'December 3, 2016 '
 'December 3, 2017 ' 'December 30, 2016 ' 'December 4, 2016 '
 'December 4, 2017 ' 'December 5, 2016 ' 'December 5, 2017 '
 'December 6, 2016 ' 'December 6, 2017 ' 'December 7, 2016 '
 'December 7, 2017 ' 'December 8, 2016 ' 'December 8, 2017 '
 'December 9, 2016 ' 'December 9, 2017 ' 'February 1, 2016 '
 'February 1, 2017 ' 'February 10, 2016 ' 'February 10, 2017 '
 'February 11, 2016 ' 'February 11, 2017 ' 'February 12, 2016 '
 'February 12, 2017 ' 'February 13, 2016 ' 'February 13, 2017 '
 'February 14, 2016 ' 'February 14, 2017 ' 'February 15, 2016 '
 'February 15, 2017 ' 'February 16, 2016 ' 'February 16, 2017 '
 'February 17, 2016 ' 'February 17, 2017 ' 'February 18, 2016 '
 'February 19, 2016 ' 'February 19, 2017 ' 'February 2, 2016 '
 'February 2, 2017 ' 'February 20, 2016 ' 'February 20, 2017 '
 'February 21, 2016 ' 'February 21, 2017 ' 'February 22, 2016 '
 'February 22, 2017 ' 'February 23, 2016 ' 'February 23, 2017 '
 'February 24, 2016 ' 'February 24, 2017 ' 'February 25, 2016 '
 'February 25, 2017 ' 'February 26, 2016 ' 'February 27, 2016 '
 'February 27, 2017 ' 'February 28, 2017 ' 'February 29, 2016 '
 'February 3, 2016 ' 'February 3, 2017 ' 'February 4, 2016 '
 'February 4, 2017 ' 'February 5, 2016 ' 'February 5, 2017 '
 'February 6, 2016 ' 'February 6, 2017 ' 'February 7, 2017 '
 'February 8, 2016 ' 'February 8, 2017 ' 'February 9, 2016 '
 'February 9, 2017 ' 'January 1, 2017 ' 'January 10, 2017 '
 'January 11, 2017 ' 'January 12, 2017 ' 'January 13, 2016 '
 'January 13, 2017 ' 'January 14, 2016 ' 'January 14, 2017 '
 'January 15, 2016 ' 'January 15, 2017 ' 'January 16, 2016 '
 'January 16, 2017 ' 'January 17, 2017 ' 'January 18, 2016 '
 'January 18, 2017 ' 'January 19, 2016 ' 'January 19, 2017 '
 'January 2, 2017 ' 'January 20, 2016 ' 'January 20, 2017 '
 'January 21, 2016 ' 'January 21, 2017 ' 'January 22, 2016 '
 'January 22, 2017 ' 'January 23, 2017 ' 'January 24, 2017 '
 'January 25, 2016 ' 'January 25, 2017 ' 'January 26, 2016 '
 'January 26, 2017 ' 'January 27, 2016 ' 'January 27, 2017 '
 'January 28, 2016 ' 'January 28, 2017 ' 'January 29, 2016 '
 'January 29, 2017 ' 'January 3, 2017 ' 'January 30, 2016 '
 'January 30, 2017 ' 'January 31, 2016 ' 'January 31, 2017 '
 'January 4, 2017 ' 'January 5, 2017 ' 'January 6, 2017 '
 'January 8, 2017 ' 'January 9, 2017 ' 'July 1, 2016 ' 'July 1, 2017 '
 'July 10, 2016 ' 'July 10, 2017 ' 'July 11, 2016 ' 'July 11, 2017 '
 'July 12, 2016 ' 'July 12, 2017 ' 'July 13, 2016 ' 'July 13, 2017 '
 'July 14, 2016 ' 'July 14, 2017 ' 'July 15, 2016 ' 'July 15, 2017 '
 'July 16, 2016 ' 'July 16, 2017 ' 'July 17, 2016 ' 'July 17, 2017 '
 'July 18, 2016 ' 'July 18, 2017 ' 'July 19, 2016 ' 'July 19, 2017 '
 'July 2, 2016 ' 'July 2, 2017 ' 'July 20, 2016 ' 'July 20, 2017 '
 'July 21, 2016 ' 'July 21, 2017 ' 'July 22, 2016 ' 'July 22, 2017 '
 'July 23, 2016 ' 'July 23, 2017 ' 'July 24, 2017 ' 'July 25, 2016 '
 'July 25, 2017 ' 'July 26, 2016 ' 'July 26, 2017 ' 'July 27, 2016 '
 'July 27, 2017 ' 'July 28, 2016 ' 'July 28, 2017 ' 'July 29, 2016 '
 'July 29, 2017 ' 'July 3, 2016 ' 'July 3, 2017 ' 'July 30, 2016 '
 'July 30, 2017 ' 'July 31, 2016 ' 'July 31, 2017 ' 'July 4, 2017 '
 'July 5, 2016 ' 'July 5, 2017 ' 'July 6, 2016 ' 'July 6, 2017 '
 'July 7, 2016 ' 'July 7, 2017 ' 'July 8, 2016 ' 'July 8, 2017 '
 'July 9, 2016 ' 'July 9, 2017 ' 'June 1, 2016 ' 'June 1, 2017 '
 'June 10, 2016 ' 'June 10, 2017 ' 'June 11, 2016 ' 'June 11, 2017 '
 'June 12, 2016 ' 'June 12, 2017 ' 'June 13, 2016 ' 'June 13, 2017 '
 'June 14, 2016 ' 'June 14, 2017 ' 'June 15, 2016 ' 'June 15, 2017 '
 'June 16, 2016 ' 'June 16, 2017 ' 'June 17, 2016 ' 'June 17, 2017 '
 'June 18, 2016 ' 'June 19, 2016 ' 'June 19, 2017 ' 'June 2, 2016 '
 'June 2, 2017 ' 'June 20, 2016 ' 'June 20, 2017 ' 'June 21, 2016 '
 'June 21, 2017 ' 'June 22, 2016 ' 'June 22, 2017 ' 'June 23, 2016 '
 'June 23, 2017 ' 'June 24, 2016 ' 'June 25, 2016 ' 'June 25, 2017 '
 'June 26, 2017 ' 'June 27, 2016 ' 'June 27, 2017 ' 'June 28, 2016 '
 'June 28, 2017 ' 'June 29, 2016 ' 'June 29, 2017 ' 'June 3, 2016 '
 'June 3, 2017 ' 'June 30, 2016 ' 'June 30, 2017 ' 'June 4, 2016 '
 'June 4, 2017 ' 'June 5, 2016 ' 'June 5, 2017 ' 'June 6, 2016 '
 'June 6, 2017 ' 'June 7, 2016 ' 'June 7, 2017 ' 'June 8, 2016 '
 'June 8, 2017 ' 'June 9, 2016 ' 'June 9, 2017 ' 'March 1, 2016 '
 'March 1, 2017 ' 'March 10, 2016 ' 'March 10, 2017 ' 'March 11, 2016 '
 'March 11, 2017 ' 'March 12, 2016 ' 'March 12, 2017 ' 'March 13, 2016 '
 'March 13, 2017 ' 'March 14, 2016 ' 'March 14, 2017 ' 'March 15, 2016 '
 'March 15, 2017 ' 'March 16, 2016 ' 'March 16, 2017 ' 'March 17, 2016 '
 'March 17, 2017 ' 'March 18, 2016 ' 'March 18, 2017 ' 'March 19, 2016 '
 'March 19, 2017 ' 'March 2, 2016 ' 'March 2, 2017 ' 'March 20, 2016 '
 'March 20, 2017 ' 'March 21, 2016 ' 'March 21, 2017 ' 'March 22, 2016 '
 'March 22, 2017 ' 'March 23, 2016 ' 'March 23, 2017 ' 'March 24, 2016 '
 'March 24, 2017 ' 'March 25, 2016 ' 'March 25, 2017 ' 'March 26, 2016 '
 'March 26, 2017 ' 'March 27, 2016 ' 'March 27, 2017 ' 'March 28, 2016 '
 'March 28, 2017 ' 'March 29, 2016 ' 'March 29, 2017 ' 'March 3, 2016 '
 'March 3, 2017 ' 'March 30, 2016 ' 'March 30, 2017 ' 'March 31, 2016 '
 'March 31, 2017 ' 'March 4, 2016 ' 'March 4, 2017 ' 'March 5, 2016 '
 'March 5, 2017 ' 'March 6, 2017 ' 'March 7, 2016 ' 'March 7, 2017 '
 'March 8, 2016 ' 'March 8, 2017 ' 'March 9, 2016 ' 'March 9, 2017 '
 'May 1, 2017 ' 'May 10, 2016 ' 'May 10, 2017 ' 'May 11, 2016 '
 'May 11, 2017 ' 'May 12, 2016 ' 'May 12, 2017 ' 'May 13, 2016 '
 'May 14, 2017 ' 'May 15, 2017 ' 'May 16, 2016 ' 'May 16, 2017 '
 'May 17, 2016 ' 'May 17, 2017 ' 'May 18, 2016 ' 'May 18, 2017 '
 'May 19, 2016 ' 'May 19, 2017 ' 'May 2, 2016 ' 'May 2, 2017 '
 'May 20, 2016 ' 'May 20, 2017 ' 'May 21, 2016 ' 'May 21, 2017 '
 'May 22, 2017 ' 'May 23, 2016 ' 'May 23, 2017 ' 'May 24, 2016 '
 'May 24, 2017 ' 'May 25, 2016 ' 'May 25, 2017 ' 'May 26, 2016 '
 'May 26, 2017 ' 'May 27, 2016 ' 'May 27, 2017 ' 'May 29, 2016 '
 'May 3, 2016 ' 'May 3, 2017 ' 'May 30, 2017 ' 'May 31, 2016 '
 'May 31, 2017 ' 'May 4, 2016 ' 'May 4, 2017 ' 'May 5, 2016 '
 'May 5, 2017 ' 'May 6, 2016 ' 'May 6, 2017 ' 'May 7, 2016 '
 'May 8, 2016 ' 'May 8, 2017 ' 'May 9, 2016 ' 'May 9, 2017 '
 'November 1, 2016 ' 'November 1, 2017 ' 'November 10, 2016 '
 'November 10, 2017 ' 'November 11, 2016 ' 'November 11, 2017 '
 'November 12, 2016 ' 'November 12, 2017 ' 'November 13, 2017 '
 'November 14, 2016 ' 'November 14, 2017 ' 'November 15, 2016 '
 'November 15, 2017 ' 'November 16, 2016 ' 'November 16, 2017 '
 'November 17, 2016 ' 'November 17, 2017 ' 'November 18, 2016 '
 'November 18, 2017 ' 'November 19, 2016 ' 'November 19, 2017 '
 'November 2, 2016 ' 'November 2, 2017 ' 'November 20, 2016 '
 'November 20, 2017 ' 'November 21, 2016 ' 'November 21, 2017 '
 'November 22, 2016 ' 'November 22, 2017 ' 'November 23, 2016 '
 'November 23, 2017 ' 'November 24, 2016 ' 'November 24, 2017 '
 'November 25, 2016 ' 'November 25, 2017 ' 'November 26, 2016 '
 'November 26, 2017 ' 'November 27, 2017 ' 'November 28, 2016 '
 'November 28, 2017 ' 'November 29, 2016 ' 'November 29, 2017 '
 'November 3, 2016 ' 'November 3, 2017 ' 'November 30, 2016 '
 'November 30, 2017 ' 'November 4, 2016 ' 'November 4, 2017 '
 'November 5, 2016 ' 'November 5, 2017 ' 'November 6, 2016 '
 'November 6, 2017 ' 'November 7, 2016 ' 'November 7, 2017 '
 'November 8, 2016 ' 'November 8, 2017 ' 'November 9, 2016 '
 'November 9, 2017 ' 'October 1, 2016 ' 'October 1, 2017 '
 'October 10, 2016 ' 'October 10, 2017 ' 'October 11, 2016 '
 'October 11, 2017 ' 'October 12, 2016 ' 'October 12, 2017 '
 'October 13, 2016 ' 'October 13, 2017 ' 'October 14, 2016 '
 'October 14, 2017 ' 'October 15, 2016 ' 'October 15, 2017 '
 'October 16, 2016 ' 'October 16, 2017 ' 'October 17, 2016 '
 'October 17, 2017 ' 'October 18, 2016 ' 'October 18, 2017 '
 'October 19, 2016 ' 'October 19, 2017 ' 'October 2, 2016 '
 'October 2, 2017 ' 'October 20, 2016 ' 'October 20, 2017 '
 'October 21, 2016 ' 'October 21, 2017 ' 'October 22, 2016 '
 'October 22, 2017 ' 'October 23, 2016 ' 'October 23, 2017 '
 'October 24, 2016 ' 'October 24, 2017 ' 'October 25, 2016 '
 'October 25, 2017 ' 'October 26, 2016 ' 'October 26, 2017 '
 'October 27, 2016 ' 'October 27, 2017 ' 'October 28, 2016 '
 'October 28, 2017 ' 'October 29, 2016 ' 'October 29, 2017 '
 'October 3, 2016 ' 'October 3, 2017 ' 'October 30, 2017 '
 'October 31, 2016 ' 'October 31, 2017 ' 'October 4, 2016 '
 'October 4, 2017 ' 'October 5, 2016 ' 'October 5, 2017 '
 'October 6, 2016 ' 'October 6, 2017 ' 'October 7, 2016 '
 'October 7, 2017 ' 'October 8, 2016 ' 'October 8, 2017 '
 'October 9, 2016 ' 'October 9, 2017 ' 'September 1, 2016 '
 'September 1, 2017 ' 'September 10, 2016 ' 'September 10, 2017 '
 'September 11, 2016 ' 'September 11, 2017 ' 'September 12, 2016 '
 'September 12, 2017 ' 'September 13, 2016 ' 'September 13, 2017 '
 'September 14, 2016 ' 'September 14, 2017 ' 'September 15, 2016 '
 'September 15, 2017 ' 'September 16, 2016 ' 'September 16, 2017 '
 'September 17, 2017 ' 'September 18, 2016 ' 'September 18, 2017 '
 'September 19, 2016 ' 'September 19, 2017 ' 'September 2, 2016 '
 'September 2, 2017 ' 'September 20, 2016 ' 'September 20, 2017 '
 'September 21, 2016 ' 'September 21, 2017 ' 'September 22, 2016 '
 'September 22, 2017 ' 'September 23, 2016 ' 'September 23, 2017 '
 'September 24, 2016 ' 'September 24, 2017 ' 'September 25, 2017 '
 'September 26, 2016 ' 'September 26, 2017 ' 'September 27, 2016 '
 'September 27, 2017 ' 'September 28, 2016 ' 'September 28, 2017 '
 'September 29, 2016 ' 'September 29, 2017 ' 'September 3, 2017 '
 'September 30, 2016 ' 'September 30, 2017 ' 'September 4, 2016 '
 'September 4, 2017 ' 'September 5, 2017 ' 'September 6, 2016 '
 'September 6, 2017 ' 'September 7, 2016 ' 'September 7, 2017 '
 'September 8, 2016 ' 'September 8, 2017 ' 'September 9, 2016 '
 'September 9, 2017 ']
Unique classes in pred: ['April 13, 2016 ' 'April 13, 2017 ' 'April 15, 2016 ' 'April 18, 2016 '
 'April 26, 2016 ' 'April 27, 2016 ' 'April 7, 2017 ' 'August 1, 2017 '
 'August 16, 2017 ' 'August 23, 2017 ' 'August 3, 2017 '
 'December 1, 2017 ' 'December 11, 2017 ' 'December 12, 2016 '
 'December 12, 2017 ' 'December 13, 2017 ' 'December 14, 2016 '
 'December 14, 2017 ' 'December 15, 2017 ' 'December 18, 2017 '
 'December 19, 2017 ' 'December 2, 2016 ' 'December 20, 2017 '
 'December 21, 2017 ' 'December 22, 2017 ' 'December 26, 2017 '
 'December 4, 2017 ' 'December 5, 2017 ' 'December 6, 2017 '
 'December 7, 2017 ' 'December 8, 2017 ' 'December 9, 2016 '
 'February 1, 2017 ' 'February 10, 2016 ' 'February 10, 2017 '
 'February 14, 2017 ' 'February 16, 2017 ' 'February 18, 2016 '
 'February 19, 2016 ' 'February 23, 2016 ' 'February 3, 2017 '
 'February 9, 2016 ' 'February 9, 2017 ' 'January 10, 2017 '
 'January 11, 2017 ' 'January 13, 2016 ' 'January 18, 2017 '
 'January 20, 2017 ' 'January 21, 2016 ' 'January 23, 2017 '
 'January 26, 2016 ' 'January 26, 2017 ' 'January 27, 2017 '
 'January 29, 2017 ' 'January 30, 2017 ' 'January 31, 2017 '
 'July 11, 2017 ' 'July 12, 2017 ' 'July 21, 2016 ' 'July 21, 2017 '
 'July 25, 2017 ' 'July 26, 2017 ' 'July 28, 2016 ' 'July 28, 2017 '
 'July 6, 2016 ' 'June 1, 2017 ' 'June 12, 2016 ' 'June 13, 2016 '
 'June 14, 2017 ' 'June 15, 2017 ' 'June 2, 2017 ' 'June 22, 2016 '
 'June 23, 2016 ' 'June 26, 2017 ' 'June 7, 2017 ' 'June 8, 2016 '
 'June 8, 2017 ' 'June 9, 2016 ' 'March 10, 2016 ' 'March 16, 2016 '
 'March 16, 2017 ' 'March 17, 2016 ' 'March 17, 2017 ' 'March 2, 2017 '
 'March 22, 2017 ' 'March 23, 2016 ' 'March 23, 2017 ' 'March 24, 2017 '
 'March 28, 2017 ' 'March 30, 2016 ' 'March 30, 2017 ' 'March 31, 2017 '
 'March 4, 2016 ' 'March 6, 2017 ' 'March 7, 2016 ' 'March 7, 2017 '
 'May 10, 2017 ' 'May 12, 2016 ' 'May 12, 2017 ' 'May 17, 2017 '
 'May 18, 2017 ' 'May 23, 2017 ' 'May 25, 2016 ' 'May 4, 2017 '
 'November 1, 2017 ' 'November 10, 2016 ' 'November 10, 2017 '
 'November 13, 2017 ' 'November 14, 2017 ' 'November 15, 2017 '
 'November 16, 2017 ' 'November 17, 2017 ' 'November 2, 2017 '
 'November 20, 2017 ' 'November 21, 2017 ' 'November 22, 2016 '
 'November 22, 2017 ' 'November 24, 2017 ' 'November 27, 2017 '
 'November 28, 2017 ' 'November 29, 2017 ' 'November 3, 2017 '
 'November 30, 2017 ' 'November 5, 2017 ' 'November 6, 2017 '
 'November 7, 2016 ' 'November 7, 2017 ' 'November 8, 2017 '
 'November 9, 2016 ' 'November 9, 2017 ' 'October 11, 2016 '
 'October 11, 2017 ' 'October 12, 2017 ' 'October 13, 2017 '
 'October 16, 2017 ' 'October 17, 2017 ' 'October 18, 2017 '
 'October 19, 2017 ' 'October 20, 2017 ' 'October 23, 2017 '
 'October 24, 2017 ' 'October 25, 2017 ' 'October 26, 2017 '
 'October 27, 2017 ' 'October 28, 2016 ' 'October 3, 2017 '
 'October 30, 2017 ' 'October 31, 2016 ' 'October 31, 2017 '
 'October 4, 2017 ' 'October 5, 2017 ' 'October 6, 2017 '
 'September 10, 2017 ' 'September 11, 2017 ' 'September 12, 2017 '
 'September 13, 2017 ' 'September 14, 2017 ' 'September 15, 2017 '
 'September 17, 2017 ' 'September 18, 2017 ' 'September 19, 2017 '
 'September 20, 2017 ' 'September 21, 2017 ' 'September 22, 2017 '
 'September 25, 2017 ' 'September 26, 2017 ' 'September 27, 2016 '
 'September 27, 2017 ' 'September 28, 2017 ' 'September 29, 2017 '
 'September 3, 2017 ' 'September 4, 2017 ' 'September 5, 2017 '
 'September 6, 2017 ' 'September 7, 2017 ' 'September 8, 2017 ']

In [49]:
# Check with .iloc instead of [0]
if isinstance(y_test.iloc[0], str) or isinstance(pred.iloc[0], str):
    mapping = {'FAKE': 0, 'REAL': 1}
    y_test = np.array([mapping[label] for label in y_test])
    pred = np.array([mapping[label] for label in pred])

KeyError: 'October 11, 2017 '

In [43]:

cm = metrics.confusion_matrix(y_test, pred, labels=[0,1])

TypeError: '<' not supported between instances of 'int' and 'str'